import { NextResponse } from 'next/server';
import { createClient, getSessionUser, getSupabaseAdmin } from '../../../../../lib/supabase';
import { generateItinerary } from '../../../../../lib/ai-integration';

/**
 * POST /api/trips/[id]/itinerary
 * Triggers AI generation for a trip, saves it to the database, and returns the complete itinerary.
 */
export async function POST(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const user = await getSessionUser();
    if (!user) {
      return NextResponse.json({ error: 'unauthorized', message: 'Authentication required' }, { status: 401 });
    }

    const tripId = params.id;
    const supabase = createClient();

    // 1. Fetch trip details & verify user ownership or collaboration permission
    const { data: trip, error: tripError } = await supabase
      .from('trips')
      .select('*')
      .eq('id', tripId)
      .single();

    if (tripError || !trip) {
      return NextResponse.json({ error: 'not_found', message: 'Trip not found.' }, { status: 404 });
    }

    // Check if user is owner or collaborator
    const { data: collaborator } = await supabase
      .from('collaborators')
      .select('*')
      .eq('trip_id', tripId)
      .eq('user_id', user.id)
      .single();

    const isOwner = trip.user_id === user.id;
    const isEditor = collaborator && collaborator.role === 'editor';

    if (!isOwner && !isEditor) {
      return NextResponse.json({ error: 'forbidden', message: 'You do not have permission to edit this trip.' }, { status: 403 });
    }

    // 2. Fetch associated trip preferences
    const { data: preferences } = await supabase
      .from('trip_preferences')
      .select('*')
      .eq('trip_id', tripId)
      .single();

    // 3. Generate Itinerary (using AI integration bridge)
    const itineraryResult = await generateItinerary({
      ...trip,
      interests: preferences?.interests_json || [],
      transportation: preferences?.transportation || 'public transit',
      accommodation: preferences?.accommodation || 'hotel',
    });

    // 4. Save the generated plans to Supabase
    const adminSupabase = getSupabaseAdmin();

    // Clean old child records
    await adminSupabase.from('daily_plans').delete().eq('trip_id', tripId);
    await adminSupabase.from('accommodations').delete().eq('trip_id', tripId);
    await adminSupabase.from('restaurants').delete().eq('trip_id', tripId);

    // Save title if generated by AI
    if (itineraryResult.trip_title) {
      await adminSupabase.from('trips').update({ title: itineraryResult.trip_title }).eq('id', tripId);
    }

    // Insert accommodations
    if (itineraryResult.accommodations && itineraryResult.accommodations.length > 0) {
      const accToSave = itineraryResult.accommodations.map((acc: any) => ({
        trip_id: tripId,
        name: acc.name,
        type: acc.type,
        price_per_night: acc.price_per_night,
        rating: acc.rating,
        lat: acc.lat,
        lng: acc.lng,
        amenities_json: acc.amenities_json || [],
        booking_url: acc.booking_url || '',
      }));
      await adminSupabase.from('accommodations').insert(accToSave);
    }

    // Insert restaurants
    if (itineraryResult.restaurants && itineraryResult.restaurants.length > 0) {
      const restToSave = itineraryResult.restaurants.map((rest: any) => ({
        trip_id: tripId,
        name: rest.name,
        cuisine: rest.cuisine,
        price_range: rest.price_range,
        rating: rest.rating,
        lat: rest.lat,
        lng: rest.lng,
        address: rest.address,
        dietary_options: rest.dietary_options || [],
        reservation_url: rest.reservation_url || '',
      }));
      await adminSupabase.from('restaurants').insert(restToSave);
    }

    // Insert daily plans & activities
    if (itineraryResult.daily_plans && itineraryResult.daily_plans.length > 0) {
      for (const plan of itineraryResult.daily_plans) {
        const { data: savedPlan, error: dpErr } = await adminSupabase
          .from('daily_plans')
          .insert({
            trip_id: tripId,
            day_number: plan.day_number,
            date: plan.date || null,
            weather_json: { condition: plan.weather_summary || 'Pleasant' },
          })
          .select()
          .single();

        if (dpErr || !savedPlan) continue;

        if (plan.activities && plan.activities.length > 0) {
          const actsToSave = plan.activities.map((act: any) => ({
            daily_plan_id: savedPlan.id,
            time_slot: act.time_slot,
            title: act.title,
            description: act.description,
            location: act.location,
            lat: act.lat,
            lng: act.lng,
            cost: act.cost,
            category: act.category,
            duration_minutes: act.duration_minutes,
            booking_url: act.booking_url || '',
          }));
          await adminSupabase.from('activities').insert(actsToSave);
        }
      }
    }

    // Fetch and return the fully populated generated itinerary
    const { data: updatedDailyPlans } = await supabase
      .from('daily_plans')
      .select(`
        *,
        activities(*)
      `)
      .eq('trip_id', tripId)
      .order('day_number', { ascending: true });

    const { data: updatedAccommodations } = await supabase.from('accommodations').select('*').eq('trip_id', tripId);
    const { data: updatedRestaurants } = await supabase.from('restaurants').select('*').eq('trip_id', tripId);

    return NextResponse.json({
      message: 'Itinerary generated successfully.',
      itinerary: {
        trip,
        daily_plans: updatedDailyPlans,
        accommodations: updatedAccommodations,
        restaurants: updatedRestaurants,
      },
    });
  } catch (err: any) {
    return NextResponse.json({ error: 'server_error', message: err.message }, { status: 500 });
  }
}
